### ISSUE TITLE
建议 数据分区，提供配置表

### ISSUE THREAD

**Issue by MRkuan** [smartmx/TFDB#1]
1.写入和读入是以扇区为单位，正常存储是按照需要存储字节为单位，所以数据分区，最好提供配置生成工具

2.最好从存储区映射内容到内存RAM区，读写对RAM区操作(加快读写)，后台写入存储区

3.如1点所述，最好提供自动生成工具进行分区存储数据

一个陌生人留言

**Comment by smartmx** [comment]
TFDB只是一个简单的存储库，因为开发中我会经常性的存储一点点数据，每次都要重新写程序来写入和读取。所以才整理出TFDB，为了以后开发更快。
存储数据多是不建议用的，TFDB特别适合资源紧张的产品，存储不是太多的信息（像IAP跳转标志、APP1/APP2运行标志，断电保存时间参数等）。
因为本身就是为了资源受限产品的，所以当时并没有考虑在RAM区存放缓存。连读写缓存都是由用户提供，TFDB连栈空间都申请的很少（最多大概使用20个字节，包括调用函数的压栈）。我开发中有过检测系统电源异常然后保存信息的需求，先写RAM然后后台再写不能满足。读取写入函数都提供了一个addr_cache的指针选项，可以加速读写的，不会每次上电都去从头开始校验读取和写入。
自动生成工具还得考虑各种单片机flash参数，包括外接的flash等等，有点复杂。更何况=.=我不太会写电脑软件。
资源足够的设备或者存储数据多的需求还是推荐使用easyflash等大型flash存储数据库，TFDB不太合适。

**Comment by MRkuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
