### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by guanjianhe** [smartmx/TFDB#3]
如果写完以后再读出来校验不成功，那么会在下个位置写；读的时候如果校验不成功，会往上一个位置读
如果写的时候没有把数据写进去，还是0xFF，那么读取到的数据将不是最新的

**Comment by guanjianhe** [comment]
如果写完以后再读出来校验不成功，那么会在下个位置写；读的时候如果校验不成功，会往上一个位置读
如果写的时候没有把数据写进去，还是0xFF，那么读取到的数据将不是最新的

**Comment by smartmx** [comment]
意思是：

**Comment by smartmx** [comment]
意思是：
重试次数中，每次都没写入，endbyte的flash值还是默认擦除后的0xff。
读取的时候，的确可能不是最新的。
当时考虑了写入错误，理论上写入错误只可能是0恢复不到1。1是必然可以写成0的，这里的确没考虑没写入的情况。

**Comment by smartmx** [comment]
目前看来有两种方案：
1. tfdb_set，每次写入后检测一下endbyte位置的数据，如果是TFDB_VALUE_AFTER_ERASE，则在相同地址重新写入。
2. tfdb_get中，从末尾开始读取。

看起来第2种更合适。

**Comment by smartmx** [comment]
@guanjianhe 已经修改，我这边测试过暂时没发现问题，有时间麻烦你也可以测一下。分支 [fix-write-skip](https://github.com/smartmx/TFDB/tree/fix-write-skip)
