### ISSUE TITLE
关于无法逆序写入的stm32L4系列问题

### ISSUE THREAD

**Issue by WangShuoran** [smartmx/TFDB#6]
https://blog.csdn.net/Fei_Yang_YF/article/details/106609610
在STM32L4中，这款芯片不能一次擦除半字节或单字节，只能擦64位/8个char双字节，或者32个双字节一行：
![image](https://github.com/smartmx/TFDB/assets/43474491/e12a3d81-64c9-437a-a5e5-6f89e7d6d826)

https://blog.csdn.net/weixin_42381351/article/details/103456465
可能因为L4的Flash编程一次性写入需要8字节(双字)，如果持续4直接写入将表现为无法逆序写入，如果每次编程写入8字节可能就没问题了。

您说的stm32L4无法逆序写入是否有其他官方资料做支撑？

**Comment by smartmx** [comment]
无法逆序写入是因为 flash eccd检查：
[st](https://community.st.com/t5/stm32-mcus-products/handling-eccd-error-during-flash-read-on-stm32l4/m-p/457070)
